"""
PROJECT EULER PROBLEM 44 - Pentagon Numbers
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However,
their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their
sum and difference are pentagonal and D = |Pk − Pj| is minimised;
what is the value of D?
"""


from math import sqrt

def P(n):
    return(int(n*(3*n-1)/2))

def iP(i,j):
    for n in range(i,j+1):
        yield(P(n))
        
""" OLD VERSION
def isP(p):
    n = 1
    while P(n) <= p:
        if P(n) == p:
            return True
        n += 1
    return False
"""
"""
    P_n = (3/2)*n**2 - (1/2)*n
      0 = (3/2)*n**2 - (1/2)*n - P_n
      a = 3/2, b = -1/2, c = -P_n
"""

A = 3/2
B = -1/2

def quadSolver(a,b,c):
    in_sqrt = b**2 - 4*a*c
    if in_sqrt < 0:
        return(["No real roots!"])
    else:
        return([(-b-sqrt(in_sqrt))/2/a,(-b+sqrt(in_sqrt))/2/a])

def isP(p):
    roots = quadSolver(A,B,-p)
    if len(roots) > 1:
        for i in roots:
            if i > 0 and i%1 == 0:
                return(True)
    return(False)


P_list = []
maxN = 4999
maxPs = int(quadSolver(A,B,-(P(maxN) + P(maxN+1)))[1])
result_list = []
for i in range(0,maxPs+1):
    P_list.append(P(i+1))

breakLoop = False
for i in range(1,maxN):
    for j in range(i+1,maxN+1):
        P_i = P_list[i]
        P_j = P_list[j]
        dP = P_j - P_i
        sP = P_j + P_i
        for item in result_list:
            if i == j-1 and dP > item:
                breakLoop = True
                break
        if isP(dP) and isP(sP):
            result_list.append(dP)
            print([i,P_i,j,P_j,dP,sP])
    if breakLoop:
        break

""" TAKES TOO LONG!
result_list = []
maxN = 100000
for i in iP(1,maxN):
    for j in iP(i,maxN):
        dP = j - i
        sP = j + i
        if isP(dP) and isP(sP):
            result_list.append([i,j,dP,sP])

print(result_list)
"""
